### ISSUE TITLE
Postfix using socket instead of TCP

### ISSUE THREAD

**Issue by Ryahn** [technicalguru/docker-mailserver-postfix#37]
docker logs mailserver_postfix
```
PF_TLS_CAFILE=/etc/postfix/CAcert.pem: File does not exist
ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
Creating user...
ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
Cannot create user postfix
```

Compose File
```
version: '3.9'

services:
  database:
    image: mariadb:10.5
    container_name: mailserver_database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: postfix
      MYSQL_USER: postfix
      MYSQL_PASSWORD: example_password
    volumes:
      - db_data:/var/lib/mysql

  postfix:
    image: technicalguru/mailserver-postfix
    container_name: mailserver_postfix
    restart: unless-stopped
    environment:
      PF_DB_HOST: localhost
      PF_DB_USER: postfix
      PF_DB_PASS: example_password
      PF_SETUP_PASS: example_root_password
      PF_MYDOMAIN: 2weekmail.fyi
      PF_MYHOSTNAME: mail.2weekmail.fyi
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    volumes:
      - postfix_data:/var/mail
      - ./config/postfix:/etc/postfix:ro

  opendkim:
    image: technicalguru/mailserver-opendkim
    container_name: mailserver_opendkim
    restart: unless-stopped
    environment:
      DKIM_SETUP_PASS: example_root_password
      DKIM_DB_HOST: localhost
      DKIM_DB_USER: postfix
      DKIM_DB_PASS: example_password
      DKIM_DB_NAME: postfix
      DKIM_DOMAIN: mail.2weekmail.fyi
      DKIM_PORT: 41001
    volumes:
      - opendkim_data:/etc/opendkim

  amavis:
    image: technicalguru/mailserver-amavis
    container_name: mailserver_amavis
    restart: unless-stopped
    ports:
      - "10024:10024"
    environment:
      - AMAVIS_LOGLEVEL=1

  postfixadmin:
    image: technicalguru/mailserver-postfixadmin
    container_name: mailserver_postfixadmin
    restart: unless-stopped
    environment:
      PFA_SETUP_PASS: example_root_password
      PFA_DB_HOST: database
      PFA_DB_USER: postfix
      PFA_DB_PASS: example_password
      PFA_DB_NAME: postfix
      RC_DES_KEY: some_special_key
      RC_IMAP_SERVER_NAME: mail.2weekmail.fyi
    ports:
      - "8080:80"

  roundcube:
    image: technicalguru/mailserver-roundcube
    container_name: mailserver_roundcube
    restart: unless-stopped
    environment:
      RC_DB_HOST: database
      RC_DB_USER: postfix
      RC_DB_PASS: example_password
      RC_DB_NAME: postfix
    ports:
      - "8081:80"
 
volumes:
  db_data:
  postfix_data:
  opendkim_data:

networks:
  mailserver_network:
    driver: bridge
```
